# Git identity account mappings used by src.switch_git_identity
# Format:
# git.account.<account_name>.username=<Git User Name>
# git.account.<account_name>.email=<Git User Email>

git.account.personal.username=kpkchaitanya
git.account.personal.email=kpkchaitanya@gmail.com

git.account.work.username=krishna-chaitanya-kondapi
git.account.work.email=krishna.chaitanya@SignetJewelers.com
